version: "3"

services:
  kylin:
    image: apachekylin/apache-kylin-standalone:4.0.0
    container_name: kylin
    ports:
      - 7070:7070 # Kylin Web UI http://localhost:7070
      - 8088:8088 # YARN Web UI http://localhost:8088
      - 50070:50070 # HDFS Web UI http://localhost:50070
      - 8032:8032
      - 8042:8042
      - 2181:2181
    volumes:
      - kylin_volume:/data
      - ./input:/input
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  kylin_volume:
